// <auto-generated />
using ApiLbWebs.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiLbWebs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200430120352_usermaillbwebs")]
    partial class usermaillbwebs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiLbWebs.Models.LBAcces", b =>
                {
                    b.Property<int>("idlb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("acc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("linkWp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passWd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userWp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idlb");

                    b.ToTable("LBAcces");
                });

            modelBuilder.Entity("ApiLbWebs.Models.LBMail", b =>
                {
                    b.Property<int>("idlbmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dnommail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lnkmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mailuser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passmail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idlbmail");

                    b.ToTable("LBMail");
                });
#pragma warning restore 612, 618
        }
    }
}
